stages:
    - Compile

variables:
    IMAGE_PREFIX: "gitlab.lrz.de:5005/sdr/docker-images/"


.tmpl_build: &tmpl_build
    tags: [build]
    dependencies: []
    stage: Compile
    script:
        - mkdir build && cd build
        - echo "Enable build generator is ${BUILD_GENERATOR}"
        - cmake -DLIBLDPC_BUILD_GENERATOR=${BUILD_GENERATOR} -DLIBLDPC_UNITTESTS=Off ../
        - make
    variables:
        BUILD_GENERATOR: "Off"

.tmpl_enable_generator: &tmpl_enable_generator
    before_script:
        - apt-get update
        - apt-get --no-install-recommends install -y libntl-dev
    variables:
        BUILD_GENERATOR: "On"



########################################################################################################################
#####
#####  Stage: Compile
#####
########################################################################################################################

Clang (Alpine):
    <<: *tmpl_build
    image: "${IMAGE_PREFIX}alpine-clang"

Clang + Generator (Ubuntu):
    <<: *tmpl_build
    <<: *tmpl_enable_generator
    image: "${IMAGE_PREFIX}ubuntu-clang"

GCC (Alpine):
    <<: *tmpl_build
    image: "${IMAGE_PREFIX}alpine-gcc"

GCC + Generator (Ubuntu):
    <<: *tmpl_build
    <<: *tmpl_enable_generator
    image: "${IMAGE_PREFIX}ubuntu-gcc"

